[package]
name = "diom-parse"
version = "0.1.0"
description = "Parses the Diom language to produce an AST"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
