[package]
name = "diom-tokens"
version = "0.1.0"

rust-version.workspace = true
edition.workspace = true
authors.workspace = true

homepage.workspace = true
repository.workspace = true
documentation.workspace = true

[dependencies]
nom = "7.1.3"
